### ISSUE TITLE
Travis CI builds are failing

### ISSUE THREAD

**Issue by jheusala** [sendanor/nor-nopg#7]
```
error: function "plv8_init" does not exist
2018-03-20 19:38:02 /home/travis/build/sendanor/nor-nopg/src/bin/nopg.js:134: 
2018-03-20 19:38:02 > error: function "plv8_init" does not exist
2018-03-20 19:38:02 >     at Connection.parseE (/home/travis/build/sendanor/nor-nopg/node_modules/nor-pg/node_modules/pg/lib/connection.js:539:11)
2018-03-20 19:38:02 >     at Connection.parseMessage (/home/travis/build/sendanor/nor-nopg/node_modules/nor-pg/node_modules/pg/lib/connection.js:366:17)
2018-03-20 19:38:02 >     at Socket.<anonymous> (/home/travis/build/sendanor/nor-nopg/node_modules/nor-pg/node_modules/pg/lib/connection.js:105:22)
2018-03-20 19:38:02 >     at emitOne (events.js:77:13)
2018-03-20 19:38:02 >     at Socket.emit (events.js:169:7)
2018-03-20 19:38:02 >     at readableAddChunk (_stream_readable.js:153:18)
2018-03-20 19:38:02 >     at Socket.Readable.push (_stream_readable.js:111:10)
2018-03-20 19:38:02 >     at TCP.onread (net.js:540:20)
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at PostgreSQL.query (/home/travis/build/sendanor/nor-nopg/node_modules/nor-extend/src/ActionObjectNoEvents.js:16:49)
2018-03-20 19:38:02 >     at module.exports (/home/travis/build/sendanor/nor-nopg/src/schema/v0001.js:17:13)
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at NorFunction.apply_ [as apply] (/home/travis/build/sendanor/nor-nopg/node_modules/nor-function/src/apply.js:139:25)
2018-03-20 19:38:02 >     at Function.p2.(anonymous function) [as then] (/home/travis/build/sendanor/nor-nopg/node_modules/nor-extend/src/extend.js:201:32)
2018-03-20 19:38:02 >     at /home/travis/build/sendanor/nor-nopg/src/nopg.js:2686:6
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at nr_fcall (/home/travis/build/sendanor/nor-nopg/node_modules/nor-newrelic/src/fcall.js:17:13)
2018-03-20 19:38:02 >     at NoPg.init (/home/travis/build/sendanor/nor-nopg/src/nopg.js:2642:33)
2018-03-20 19:38:02 >     at NorFunction.apply_ [as apply] (/home/travis/build/sendanor/nor-nopg/node_modules/nor-function/src/apply.js:138:25)
2018-03-20 19:38:02 >     at /home/travis/build/sendanor/nor-nopg/node_modules/nor-extend/src/extend.js:227:90
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at NorFunction.apply_ [as apply] (/home/travis/build/sendanor/nor-nopg/node_modules/nor-function/src/apply.js:139:25)
2018-03-20 19:38:02 >     at Function.p2.(anonymous function) [as then] (/home/travis/build/sendanor/nor-nopg/node_modules/nor-extend/src/extend.js:201:32)
2018-03-20 19:38:02 >     at action_init (/home/travis/build/sendanor/nor-nopg/src/bin/nopg.js:52:46)
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at /home/travis/build/sendanor/nor-nopg/src/bin/nopg.js:115:14
2018-03-20 19:38:02 > From previous event:
2018-03-20 19:38:02 >     at Object.<anonymous> (/home/travis/build/sendanor/nor-nopg/src/bin/nopg.js:126:4)
2018-03-20 19:38:02 >     at node.js:1043:3
2018-03-20 19:38:02 > > name = error
2018-03-20 19:38:02 > > length = 83
2018-03-20 19:38:02 > > severity = ERROR
2018-03-20 19:38:02 > > code = 42883
2018-03-20 19:38:02 > > file = regproc.c
2018-03-20 19:38:02 > > line = 144
2018-03-20 19:38:02 > > routine = regprocin
The command "./src/bin/nopg.js -v init" failed and exited with 1 during .
```

See https://travis-ci.org/sendanor/nor-nopg/jobs/356023592

My local `npm test` was running tests correctly.

**Comment by juhovh** [comment]
I am not completely sure why it works on your local machine, but what appears to be the issue on travis is that in file https://github.com/sendanor/nor-nopg/blob/master/src/schema/v0001.js it tries to create a `check_javascript(js text)` function, which in turn tries to call `plv8_init()`, which in turn does not exist yet since it is created in https://github.com/sendanor/nor-nopg/blob/master/src/schema/v0002.js. Also 

I believe this database schema has gotten into an inconsistent state because when v0001.js and v0002.js were written the `"SET plv8.start_proc = 'plv8_init'` line was not yet in its current location. Also v0001.js and v0002.js cannot be swapped with each other since v0002.js refers to `check_javascript(js text)` function defined in v0001.js, modifying database schema history is not a good idea anyway.

However, since the `plv8_init()` function is defined with `CREATE OR REPLACE FUNCTION` one can quite easily work around this issue in travis by simply defining a no-op `plv8_init()` function that will be later replaced by v0002.js and all tests pass just fine and dandy! See the diff below that is tested to work:

```
   - psql template1 -c 'CREATE EXTENSION moddatetime;' -U postgres
   - psql -c 'CREATE DATABASE nopg_test;' -U postgres
+  - psql nopg_test -c 'CREATE FUNCTION plv8_init() RETURNS boolean LANGUAGE plv8 VOLATILE AS $$ return true; $$;' -U postgres
   - ./src/bin/nopg.js -v init
 after_failure:
```

**Comment by juhovh** [comment]
As a side note, one could maybe add the no-op plv8_init() function creation to v0000.js or v0001.js so that this bug wouldn’t happen for users with a clean database either. Just fixing the Travis tests might not be sufficient.
